# Generated by Django 4.0 on 2021-12-26 13:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
